site_name: CellViability
repo_url: https://github.com/cnpem/CellViability
site_url: https://cnpem.github.io/CellViability
site_description: A Python package to assess cell viability in microscopy images using deep learning models for drug screening.
site_author: João V. S. Guerra
edit_uri: edit/main/docs/
repo_name: cnpem/CellViability
copyright: Maintained by <a href="https://cnpem.github.io">CNPEM</a>.

nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial: tutorial.md
  - API Reference: api.md
  - Config.json: config_json.md
  - About: about.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["CellViability"]
theme:
  name: readthedocs
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cnpem/CellViability
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/CellViability

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
