[project]
name = "kayllany-oliveira"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bioio>=0.0.1",
    "bioio-ome-tiff>=1.0.2",
    "bioio-ome-zarr>=1.1.2",
    "cellpose>=3.0.9",
    "certifi>=2025.1.31",
    "csbdeep>=0.8.1",
    "imageio>=2.37.0",
    "matplotlib>=3.10.1",
    "numpy>=1.26.0,<2.2.0",
    "pandas>=2.2.3",
    "pip-system-certs>=5.2",
    "scikit-image>=0.25.2",
    "scipy>=1.15.2",
    "stardist>=0.9.1",
    "tensorflow>=2.18.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "jupyterlab>=4.4.0",
    "notebook>=7.0.7",
]
